-- Inserts for the first 50 Pokémon
INSERT INTO pokemon (name, type) VALUES
  ('Bulbasaur', ARRAY['Grass', 'Poison']),
  ('Ivysaur', ARRAY['Grass', 'Poison']),
  ('Venusaur', ARRAY['Grass', 'Poison']),
  ('Charmander', ARRAY['Fire']),
  ('Charmeleon', ARRAY['Fire']),
  ('Charizard', ARRAY['Fire', 'Flying']),
  ('Squirtle', ARRAY['Water']),
  ('Wartortle', ARRAY['Water']),
  ('Blastoise', ARRAY['Water']),
  ('Caterpie', ARRAY['Bug']),
  ('Metapod', ARRAY['Bug']),
  ('Butterfree', ARRAY['Bug', 'Flying']),
  ('Weedle', ARRAY['Bug', 'Poison']),
  ('Kakuna', ARRAY['Bug', 'Poison']),
  ('Beedrill', ARRAY['Bug', 'Poison']),
  ('Pidgey', ARRAY['Normal', 'Flying']),
  ('Pidgeotto', ARRAY['Normal', 'Flying']),
  ('Pidgeot', ARRAY['Normal', 'Flying']),
  ('Rattata', ARRAY['Normal']),
  ('Raticate', ARRAY['Normal']),
  ('Spearow', ARRAY['Normal', 'Flying']),
  ('Fearow', ARRAY['Normal', 'Flying']),
  ('Ekans', ARRAY['Poison']),
  ('Arbok', ARRAY['Poison']),
  ('Pikachu', ARRAY['Electric']),
  ('Raichu', ARRAY['Electric']),
  ('Sandshrew', ARRAY['Ground']),
  ('Sandslash', ARRAY['Ground']),
  ('Nidoran (M)', ARRAY['Poison']),
  ('Nidorina', ARRAY['Poison']),
  ('Nidoqueen', ARRAY['Poison', 'Ground']),
  ('Nidoran (F)', ARRAY['Poison']),
  ('Nidorino', ARRAY['Poison']),
  ('Nidoking', ARRAY['Poison', 'Ground']),
  ('Clefairy', ARRAY['Fairy']),
  ('Clefable', ARRAY['Fairy']),
  ('Vulpix', ARRAY['Fire']),
  ('Ninetales', ARRAY['Fire']),
  ('Jigglypuff', ARRAY['Normal', 'Fairy']),
  ('Wigglytuff', ARRAY['Normal', 'Fairy']),
  ('Zubat', ARRAY['Poison', 'Flying']),
  ('Golbat', ARRAY['Poison', 'Flying']),
  ('Oddish', ARRAY['Grass', 'Poison']),
  ('Gloom', ARRAY['Grass', 'Poison']),
  ('Vileplume', ARRAY['Grass', 'Poison']),
  ('Paras', ARRAY['Bug', 'Grass']),
  ('Parasect', ARRAY['Bug', 'Grass']),
  ('Venonat', ARRAY['Bug', 'Poison']),
  ('Venomoth', ARRAY['Bug', 'Poison']);
